spring.application.name: app

spring:
  jackson.mapper.accept-case-insensitive-enums: true

logging.level.org.springframework.transaction: trace
logging.level.org.springframework.kafka.transaction: debug
logging.level.org.springframework.jdbc: debug  